# parking-service/docker-compose.yml
version: '3.8'

services:
  parking-service:
    container_name: parking-service
    build: .
    ports:
      - "5002:5002"
    environment:
      - PORT=5002
      - MONGO_URI=mongodb://mongo:27017/parking_db
      - JWT_SECRET=supersecretkey
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: parking-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
