version: "3.8"

services:
  user-service:
    container_name: user-service
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=useradmin
      - DB_PASSWORD=secret
      - DB_NAME=userdb
      - JWT_SECRET=supersecretkey
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: user_pg
    environment:
      POSTGRES_USER: useradmin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: userdb
    volumes:
      - user_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  user_pg_data:
